# Start AethelOS — one-click launcher (Windows). Run from repo root:
#   .\scripts\start-aethelos.ps1
#   .\scripts\start-aethelos.ps1 -Mode Browser
#   .\scripts\start-aethelos.ps1 -Lan
param(
    [ValidateSet("Auto", "Docker", "Desktop", "Browser")]
    [string]$Mode = "Auto",
    [switch]$Lan
)

$ErrorActionPreference = "Stop"
$Root = Split-Path $PSScriptRoot -Parent
Set-Location $Root
$env:Path = "$env:USERPROFILE\.cargo\bin;" + $env:Path

function Write-ShareCard {
    param([string]$AppUrl, [string]$RelayWs)
    $lanIp = Get-LanIPv4
    Write-Host ""
    Write-Host "=== AethelOS is running ===" -ForegroundColor Green
    Write-Host "  Open locally:  $AppUrl"
    if ($lanIp) {
        $lanApp = $AppUrl -replace "localhost|127\.0\.0\.1", $lanIp
        $lanRelay = $RelayWs -replace "localhost|127\.0\.0\.1", $lanIp
        Write-Host "  Share on LAN:  $lanApp"
        Write-Host "  LAN relay:     $lanRelay"
    }
    Write-Host "  Invite friends: Community tab -> Share invite link"
    Write-Host ""
}

function Get-LanIPv4 {
    $addr = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object {
            $_.IPAddress -notmatch "^127\." -and
            $_.PrefixOrigin -ne "WellKnown"
        } |
        Sort-Object InterfaceMetric |
        Select-Object -First 1 -ExpandProperty IPAddress
    return $addr
}

function Test-CommandExists([string]$Name) {
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ensure-Pnpm {
    if (-not (Test-CommandExists "pnpm")) {
        if (-not (Test-CommandExists "node")) {
            Write-Host "Node.js not found. Install Node 20 LTS:" -ForegroundColor Yellow
            Write-Host "  winget install OpenJS.NodeJS.LTS"
            exit 1
        }
        Write-Host "Installing pnpm..."
        corepack enable
        corepack prepare pnpm@9.15.0 --activate
    }
}

function Ensure-Dependencies {
    if (-not (Test-Path "$Root\node_modules")) {
        Write-Host "First run — installing dependencies (one time)..."
        pnpm install
    }
}

function Ensure-RelayBuilt {
    $relayScript = "$Root\packages\relay\dist\index.js"
    if (-not (Test-Path $relayScript)) {
        Write-Host "Building relay sidecar..."
        pnpm --filter @aethelos/relay build
    }
}

function Write-DockerEnv {
    param([switch]$UseLan)
    $lanIp = if ($UseLan) { Get-LanIPv4 } else { $null }
    $hostName = if ($lanIp) { $lanIp } else { "localhost" }
    @"
# Generated by Start-AethelOS.ps1 — rebuild client if you change LAN IP (-Lan)
VITE_DEFAULT_RELAY_URL=ws://${hostName}:8787
VITE_INVITE_BASE_URL=http://${hostName}:8080
"@ | Set-Content -Path "$Root\.env.docker" -Encoding utf8
    Write-Host "Docker build env: VITE_INVITE_BASE_URL=http://${hostName}:8080"
}

function Test-DockerReady {
    if (-not (Test-CommandExists "docker")) { return $false }
    try {
        docker info 2>$null | Out-Null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Test-DesktopReady {
    if (-not (Test-CommandExists "rustc")) { return $false }
    if (-not (Test-CommandExists "cargo")) { return $false }
    return $true
}

function Start-DockerStack {
    if ($Lan) { Write-DockerEnv -UseLan } else { Write-DockerEnv }
    Write-Host "Starting Docker stack (relay + browser app)..."
    docker compose --env-file .env.docker up --build -d
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Start-Sleep -Seconds 3
    Start-Process "http://localhost:8080"
    Write-ShareCard -AppUrl "http://localhost:8080" -RelayWs "ws://localhost:8787"
    Write-Host "Logs: docker compose logs -f"
    Write-Host "Stop:  docker compose down"
}

function Start-BrowserDev {
    Ensure-Pnpm
    Ensure-Dependencies
    Ensure-RelayBuilt
    Write-ShareCard -AppUrl "http://localhost:5173" -RelayWs "ws://localhost:8787"
    Write-Host "Starting relay and browser client (Ctrl+C to stop)..."
    $relayJob = Start-Job -ScriptBlock {
        Set-Location $using:Root
        pnpm dev:relay 2>&1
    }
    Start-Sleep -Seconds 2
    try {
        Start-Process "http://localhost:5173"
        pnpm dev:client
    } finally {
        Stop-Job $relayJob -ErrorAction SilentlyContinue
        Remove-Job $relayJob -Force -ErrorAction SilentlyContinue
    }
}

function Start-DesktopDev {
    Ensure-Pnpm
    Ensure-Dependencies
    Ensure-RelayBuilt
    if (-not (Test-CommandExists "cloudflared")) {
        Write-Host "cloudflared not found — local network only until installed:" -ForegroundColor Yellow
        Write-Host "  winget install Cloudflare.cloudflared"
    }
    Write-ShareCard -AppUrl "http://localhost:5173 (desktop window)" -RelayWs "ws://localhost:8787"
    Write-Host "Starting desktop app..."
    pnpm --filter @aethelos/client-tauri desktop:dev
}

# --- main ---
Write-Host "AethelOS launcher" -ForegroundColor Cyan

$selected = $Mode
if ($selected -eq "Auto") {
    if (Test-DockerReady) {
        $selected = "Docker"
    } elseif (Test-DesktopReady) {
        $selected = "Desktop"
    } else {
        $selected = "Browser"
    }
    Write-Host "Auto-selected mode: $selected"
}

switch ($selected) {
    "Docker" {
        if (-not (Test-DockerReady)) {
            Write-Host "Docker not available. Install Docker Desktop:" -ForegroundColor Yellow
            Write-Host "  https://www.docker.com/products/docker-desktop/"
            Write-Host "Falling back to browser dev mode..."
            Start-BrowserDev
        } else {
            Start-DockerStack
        }
    }
    "Desktop" {
        if (-not (Test-DesktopReady)) {
            Write-Host "Rust not found. Install from https://rustup.rs/ or use Browser mode." -ForegroundColor Yellow
            Start-BrowserDev
        } else {
            Start-DesktopDev
        }
    }
    "Browser" {
        Start-BrowserDev
    }
}
