# Start AethelOS - one-click launcher (Windows). Run from repo root:
#   .\scripts\start-aethelos.ps1
#   .\scripts\start-aethelos.ps1 -Share
#   .\scripts\start-aethelos.ps1 -Lan
#   .\scripts\start-aethelos.ps1 -Mode Docker   # publisher / CI only
param(
    [ValidateSet("Auto", "Release", "Desktop", "Browser", "Docker")]
    [string]$Mode = "Auto",
    [switch]$Lan,
    [switch]$Share
)

$ErrorActionPreference = "Stop"
$Root = Split-Path $PSScriptRoot -Parent
Set-Location $Root
$env:Path = "$env:USERPROFILE\.cargo\bin;" + $env:Path

function Write-ShareCard {
    param([string]$AppUrl, [string]$PublicUrl)
    $lanIp = Get-LanIPv4
    Write-Host ""
    Write-Host "=== AethelOS is running ===" -ForegroundColor Green
    Write-Host "  Open locally:  $AppUrl"
    if ($PublicUrl) {
        Write-Host "  Share link:    $PublicUrl" -ForegroundColor Cyan
        Write-Host "  (Open on your phone - same link - to start a community and invite others)"
    } elseif ($lanIp) {
        Write-Host "  Share on Wi-Fi: http://${lanIp}:8080"
    } else {
        Write-Host "  Share link:    see Connection tab in the app"
    }
    Write-Host "  Then: Community -> Invite people"
    Write-Host ""
}

function Get-LanIPv4 {
    $addr = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object {
            $_.IPAddress -notmatch "^127\." -and
            $_.PrefixOrigin -ne "WellKnown"
        } |
        Sort-Object InterfaceMetric |
        Select-Object -First 1 -ExpandProperty IPAddress
    return $addr
}

function Test-CommandExists([string]$Name) {
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ensure-Pnpm {
    if (-not (Test-CommandExists "pnpm")) {
        if (-not (Test-CommandExists "node")) {
            Write-Host "Node.js not found. Install Node 20 LTS:" -ForegroundColor Yellow
            Write-Host "  winget install OpenJS.NodeJS.LTS"
            exit 1
        }
        Write-Host "Installing pnpm..."
        corepack enable
        corepack prepare pnpm@9.15.0 --activate
    }
}

function Ensure-Dependencies {
    if (-not (Test-Path "$Root\node_modules")) {
        Write-Host "First run - installing dependencies (one time)..."
        pnpm install
    }
}

function Ensure-RelayBuilt {
    $relayScript = "$Root\packages\relay\dist\index.js"
    if (-not (Test-Path $relayScript)) {
        Write-Host "Building relay..."
        pnpm --filter @aethelos/relay build
    }
}

function Find-AethelosExe {
    $candidates = @(
        (Join-Path $Root "packages\client-tauri\src-tauri\target\release\aethelos-desktop.exe"),
        (Join-Path $env:LOCALAPPDATA "AethelOS\AethelOS.exe"),
        (Join-Path $env:LOCALAPPDATA "org.aethelos.desktop\AethelOS.exe")
    )
    foreach ($p in $candidates) {
        if (Test-Path $p) { return $p }
    }
    return $null
}

function Test-ReleaseReady {
    return [bool](Find-AethelosExe)
}

function Test-DesktopReady {
    return (Test-CommandExists "rustc") -and (Test-CommandExists "cargo")
}

function Test-DockerReady {
    if ($env:AETHELOS_USE_DOCKER -ne "1" -and $Mode -ne "Docker") { return $false }
    if (-not (Test-CommandExists "docker")) { return $false }
    try {
        docker info 2>$null | Out-Null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Write-DockerEnv {
    $envPath = Join-Path $Root ".env.docker"
    @(
        "# Generated by Start-AethelOS.ps1 - publisher/CI only"
        "VITE_DEFAULT_RELAY_URL="
        "VITE_BOOTSTRAP_RELAYS="
        "VITE_INVITE_BASE_URL="
    ) | Set-Content -Path $envPath -Encoding utf8
}

function Start-PublicShare {
    & (Join-Path $Root "scripts\share-public.ps1")
    if (Test-Path (Join-Path $Root ".share-url")) {
        return (Get-Content (Join-Path $Root ".share-url") -Raw).Trim()
    }
    return $null
}

function Start-ReleaseApp {
    $exe = Find-AethelosExe
    if (-not $exe) { return $false }
    Write-Host "Opening AethelOS..."
    Start-Process $exe
    Write-ShareCard -AppUrl "AethelOS window" -PublicUrl $null
    Write-Host "Share link appears in the app under Connection."
    return $true
}

function Start-DockerStack {
    Write-DockerEnv
    Write-Host "Starting publisher stack (internal)..."
    docker compose --env-file .env.docker up --build -d
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Start-Sleep -Seconds 4

    $publicUrl = $null
    if ($Share -or -not $Lan) {
        $publicUrl = Start-PublicShare
    }

    Start-Process "http://localhost:8080"
    Write-ShareCard -AppUrl "http://localhost:8080" -PublicUrl $publicUrl
    Write-Host "Stop: docker compose down"
}

function Start-BrowserDev {
    Ensure-Pnpm
    Ensure-Dependencies
    Ensure-RelayBuilt
    Write-ShareCard -AppUrl "http://localhost:5173" -PublicUrl $null
    Write-Host "Starting relay and browser client (Ctrl+C to stop)..."
    $relayJob = Start-Job -ScriptBlock {
        Set-Location $using:Root
        pnpm dev:relay 2>&1
    }
    Start-Sleep -Seconds 2
    try {
        Start-Process "http://localhost:5173"
        pnpm dev:client
    } finally {
        Stop-Job $relayJob -ErrorAction SilentlyContinue
        Remove-Job $relayJob -Force -ErrorAction SilentlyContinue
    }
}

function Start-DesktopDev {
    Ensure-Pnpm
    Ensure-Dependencies
    Ensure-RelayBuilt
    Write-ShareCard -AppUrl "AethelOS window" -PublicUrl $null
    Write-Host "Starting desktop app..."
    pnpm --filter @aethelos/client-tauri desktop:dev
}

# --- main ---
Write-Host "AethelOS" -ForegroundColor Cyan

$selected = $Mode
if ($selected -eq "Auto") {
    if (Test-ReleaseReady) {
        $selected = "Release"
    } elseif (Test-DesktopReady) {
        $selected = "Desktop"
    } elseif (Test-DockerReady) {
        $selected = "Docker"
    } else {
        $selected = "Browser"
    }
    Write-Host "Mode: $selected"
}

switch ($selected) {
    "Release" {
        if (-not (Start-ReleaseApp)) {
            Write-Host "No release build found. Run Build-Release.bat or use desktop dev." -ForegroundColor Yellow
            if (Test-DesktopReady) { Start-DesktopDev } else { Start-BrowserDev }
        }
    }
    "Docker" {
        if (-not (Test-DockerReady)) {
            Write-Host "Docker not available." -ForegroundColor Yellow
            if (Test-DesktopReady) { Start-DesktopDev } else { Start-BrowserDev }
        } else {
            Start-DockerStack
        }
    }
    "Desktop" {
        if (-not (Test-DesktopReady)) {
            Start-BrowserDev
        } else {
            Start-DesktopDev
        }
    }
    "Browser" { Start-BrowserDev }
}
